package:
  name: duckdb-operator-replacement
  version: 0.0.1

source:
  - path: .
    use_gitignore: true
    target_directory: operator-replacement-src

build:
  number: 0
  script: |
    set -ex
    
    # Build operator replacement extension using DuckDB from duckdb-from-source package
    cd $SRC_DIR/operator-replacement-src
    
    mkdir -p build
    cd build
    
    # Compile C++ sources (DuckDB headers are in $PREFIX/include from duckdb-from-source)
    $CXX -std=c++17 -fPIC -O2 \
      -I${PREFIX}/include \
      -c ../duckdb_operator_replacement.cpp \
      -o duckdb_operator_replacement.o
    
    $CXX -std=c++17 -fPIC -O2 \
      -I${PREFIX}/include \
      -c ../duckdb_operator_replacement_wrapper.cpp \
      -o duckdb_operator_replacement_wrapper.o
    
    $CXX -std=c++17 -fPIC -O2 \
      -I${PREFIX}/include \
      -c ../test_functions.cpp \
      -o test_functions.o
    
    # Build shared library (DuckDB library is in $PREFIX/lib from duckdb-from-source)
    if [[ "$OSTYPE" == "darwin"* ]]; then
      $CXX -shared -fPIC \
        duckdb_operator_replacement.o \
        duckdb_operator_replacement_wrapper.o \
        test_functions.o \
        -L${PREFIX}/lib \
        -lduckdb \
        -o libduckdb_operator_replacement.dylib \
        -Wl,-rpath,@loader_path
    else
      $CXX -shared -fPIC \
        duckdb_operator_replacement.o \
        duckdb_operator_replacement_wrapper.o \
        test_functions.o \
        -L${PREFIX}/lib \
        -lduckdb \
        -o libduckdb_operator_replacement.so \
        -Wl,-rpath,'$ORIGIN'
    fi
    
    # Build test executable
    $CC -std=c11 -O2 \
      -I${PREFIX}/include \
      ../test_operator_replacement.c \
      duckdb_operator_replacement.o \
      duckdb_operator_replacement_wrapper.o \
      test_functions.o \
      -L${PREFIX}/lib \
      -lduckdb \
      -lstdc++ \
      -o test_operator_replacement
    
    # Install shared library
    mkdir -p $PREFIX/lib
    cp libduckdb_operator_replacement.* $PREFIX/lib/
    
    # Install Mojo bindings
    mkdir -p $PREFIX/lib/mojo
    cp -r ../src $PREFIX/lib/mojo/operator_replacement
    
    # Install examples
    mkdir -p $PREFIX/share/operator_replacement
    cp -r ../examples $PREFIX/share/operator_replacement/

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja

  host:
    - duckdb-from-source ==1.4.4

  run:
    - duckdb-from-source ==1.4.4